FROM --platform=$BUILDPLATFORM rust:alpine AS builder

RUN apk add --no-cache protoc protobuf-dev

WORKDIR /app
COPY protobuf/ ./protobuf/
COPY webui/bff/ ./webui/bff/

WORKDIR /app/webui/bff
ARG TARGETARCH

RUN case "$TARGETARCH" in \
      "amd64") RUST_TARGET="x86_64-unknown-linux-musl" ;; \
      "arm64") RUST_TARGET="aarch64-unknown-linux-musl" ;; \
      *) echo "Unsupported architecture: $TARGETARCH"; exit 1 ;; \
    esac && \
    rustup target add $RUST_TARGET && \
    cargo build --release --target $RUST_TARGET && \
    cp target/$RUST_TARGET/release/beemon-bff /app/beemon-bff

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/beemon-bff .
CMD ["./beemon-bff"]
