FROM --platform=$BUILDPLATFORM golang:1.26-alpine AS builder

WORKDIR /app
COPY protobuf/ ./protobuf/
COPY webui/bff/ ./webui/bff/

WORKDIR /app/webui/bff
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=linux GOARCH=$TARGETARCH go build -o /app/beemon-bff .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/beemon-bff .
CMD ["./beemon-bff"]
