// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BeemonEventT struct {
	_       structs.HostLayout
	Pid     uint32
	Tgid    uint32
	Type    uint32
	_       [4]byte
	Ts      uint64
	Syscall struct {
		_         structs.HostLayout
		SyscallId uint32
	}
	File struct {
		_        structs.HostLayout
		Filename [256]int8
		Flags    int32
	}
	Net struct {
		_      structs.HostLayout
		Saddr  uint32
		Daddr  uint32
		Sport  uint16
		Dport  uint16
		Family uint16
		_      [2]byte
	}
	Process struct {
		_        structs.HostLayout
		ChildPid uint32
		ExitCode int32
		Comm     [16]int8
		IsExit   uint8
		IsExec   uint8
		IsFork   uint8
		ArgCount uint8
		Filename [256]int8
		Args     [6][64]int8
	}
	_  [4]byte
	Rw struct {
		_     structs.HostLayout
		Fd    uint32
		_     [4]byte
		Count uint64
		Data  [256]int8
	}
	Close struct {
		_  structs.HostLayout
		Fd uint32
	}
	_ [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	BeemonMapEvents                 = "events"
	BeemonMapTargetPids             = "target_pids"
	BeemonProgTcpV4Connect          = "tcp_v4_connect"
	BeemonProgTraceSchedProcessExit = "trace_sched_process_exit"
	BeemonProgTraceSchedProcessFork = "trace_sched_process_fork"
	BeemonProgTraceSysEnterClose    = "trace_sys_enter_close"
	BeemonProgTraceSysEnterExecve   = "trace_sys_enter_execve"
	BeemonProgTraceSysEnterOpenat   = "trace_sys_enter_openat"
	BeemonProgTraceSysEnterRead     = "trace_sys_enter_read"
	BeemonProgTraceSysEnterWrite    = "trace_sys_enter_write"
	BeemonVarEventT_forceBtf        = "_event_t_force_btf"
)

// LoadBeemon returns the embedded CollectionSpec for Beemon.
func LoadBeemon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BeemonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Beemon: %w", err)
	}

	return spec, err
}

// LoadBeemonObjects loads Beemon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BeemonObjects
//	*BeemonPrograms
//	*BeemonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBeemonObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBeemon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BeemonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BeemonSpecs struct {
	BeemonProgramSpecs
	BeemonMapSpecs
	BeemonVariableSpecs
}

// BeemonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BeemonProgramSpecs struct {
	TcpV4Connect          *ebpf.ProgramSpec `ebpf:"tcp_v4_connect"`
	TraceSchedProcessExit *ebpf.ProgramSpec `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork *ebpf.ProgramSpec `ebpf:"trace_sched_process_fork"`
	TraceSysEnterClose    *ebpf.ProgramSpec `ebpf:"trace_sys_enter_close"`
	TraceSysEnterExecve   *ebpf.ProgramSpec `ebpf:"trace_sys_enter_execve"`
	TraceSysEnterOpenat   *ebpf.ProgramSpec `ebpf:"trace_sys_enter_openat"`
	TraceSysEnterRead     *ebpf.ProgramSpec `ebpf:"trace_sys_enter_read"`
	TraceSysEnterWrite    *ebpf.ProgramSpec `ebpf:"trace_sys_enter_write"`
}

// BeemonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BeemonMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	TargetPids *ebpf.MapSpec `ebpf:"target_pids"`
}

// BeemonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BeemonVariableSpecs struct {
	EventT_forceBtf *ebpf.VariableSpec `ebpf:"_event_t_force_btf"`
}

// BeemonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBeemonObjects or ebpf.CollectionSpec.LoadAndAssign.
type BeemonObjects struct {
	BeemonPrograms
	BeemonMaps
	BeemonVariables
}

func (o *BeemonObjects) Close() error {
	return _BeemonClose(
		&o.BeemonPrograms,
		&o.BeemonMaps,
	)
}

// BeemonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBeemonObjects or ebpf.CollectionSpec.LoadAndAssign.
type BeemonMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	TargetPids *ebpf.Map `ebpf:"target_pids"`
}

func (m *BeemonMaps) Close() error {
	return _BeemonClose(
		m.Events,
		m.TargetPids,
	)
}

// BeemonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBeemonObjects or ebpf.CollectionSpec.LoadAndAssign.
type BeemonVariables struct {
	EventT_forceBtf *ebpf.Variable `ebpf:"_event_t_force_btf"`
}

// BeemonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBeemonObjects or ebpf.CollectionSpec.LoadAndAssign.
type BeemonPrograms struct {
	TcpV4Connect          *ebpf.Program `ebpf:"tcp_v4_connect"`
	TraceSchedProcessExit *ebpf.Program `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork *ebpf.Program `ebpf:"trace_sched_process_fork"`
	TraceSysEnterClose    *ebpf.Program `ebpf:"trace_sys_enter_close"`
	TraceSysEnterExecve   *ebpf.Program `ebpf:"trace_sys_enter_execve"`
	TraceSysEnterOpenat   *ebpf.Program `ebpf:"trace_sys_enter_openat"`
	TraceSysEnterRead     *ebpf.Program `ebpf:"trace_sys_enter_read"`
	TraceSysEnterWrite    *ebpf.Program `ebpf:"trace_sys_enter_write"`
}

func (p *BeemonPrograms) Close() error {
	return _BeemonClose(
		p.TcpV4Connect,
		p.TraceSchedProcessExit,
		p.TraceSchedProcessFork,
		p.TraceSysEnterClose,
		p.TraceSysEnterExecve,
		p.TraceSysEnterOpenat,
		p.TraceSysEnterRead,
		p.TraceSysEnterWrite,
	)
}

func _BeemonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed beemon_x86_bpfel.o
var _BeemonBytes []byte
