// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BeemonEventT struct {
	_       structs.HostLayout
	Pid     uint32
	Tgid    uint32
	Type    uint32
	_       [4]byte
	Ts      uint64
	Syscall struct {
		_         structs.HostLayout
		SyscallId uint32
	}
	_ [256]byte
	_ [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	BeemonMapEvents                 = "events"
	BeemonMapTargetPids             = "target_pids"
	BeemonProgDoSysOpenat2          = "do_sys_openat2"
	BeemonProgTcpV4Connect          = "tcp_v4_connect"
	BeemonProgTraceSchedProcessExec = "trace_sched_process_exec"
	BeemonProgTraceSchedProcessExit = "trace_sched_process_exit"
	BeemonProgTraceSchedProcessFork = "trace_sched_process_fork"
	BeemonProgTraceSysEnter         = "trace_sys_enter"
	BeemonVarEventT_forceBtf        = "_event_t_force_btf"
)

// LoadBeemon returns the embedded CollectionSpec for Beemon.
func LoadBeemon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BeemonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Beemon: %w", err)
	}

	return spec, err
}

// LoadBeemonObjects loads Beemon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BeemonObjects
//	*BeemonPrograms
//	*BeemonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBeemonObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBeemon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BeemonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BeemonSpecs struct {
	BeemonProgramSpecs
	BeemonMapSpecs
	BeemonVariableSpecs
}

// BeemonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BeemonProgramSpecs struct {
	DoSysOpenat2          *ebpf.ProgramSpec `ebpf:"do_sys_openat2"`
	TcpV4Connect          *ebpf.ProgramSpec `ebpf:"tcp_v4_connect"`
	TraceSchedProcessExec *ebpf.ProgramSpec `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit *ebpf.ProgramSpec `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork *ebpf.ProgramSpec `ebpf:"trace_sched_process_fork"`
	TraceSysEnter         *ebpf.ProgramSpec `ebpf:"trace_sys_enter"`
}

// BeemonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BeemonMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	TargetPids *ebpf.MapSpec `ebpf:"target_pids"`
}

// BeemonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BeemonVariableSpecs struct {
	EventT_forceBtf *ebpf.VariableSpec `ebpf:"_event_t_force_btf"`
}

// BeemonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBeemonObjects or ebpf.CollectionSpec.LoadAndAssign.
type BeemonObjects struct {
	BeemonPrograms
	BeemonMaps
	BeemonVariables
}

func (o *BeemonObjects) Close() error {
	return _BeemonClose(
		&o.BeemonPrograms,
		&o.BeemonMaps,
	)
}

// BeemonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBeemonObjects or ebpf.CollectionSpec.LoadAndAssign.
type BeemonMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	TargetPids *ebpf.Map `ebpf:"target_pids"`
}

func (m *BeemonMaps) Close() error {
	return _BeemonClose(
		m.Events,
		m.TargetPids,
	)
}

// BeemonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBeemonObjects or ebpf.CollectionSpec.LoadAndAssign.
type BeemonVariables struct {
	EventT_forceBtf *ebpf.Variable `ebpf:"_event_t_force_btf"`
}

// BeemonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBeemonObjects or ebpf.CollectionSpec.LoadAndAssign.
type BeemonPrograms struct {
	DoSysOpenat2          *ebpf.Program `ebpf:"do_sys_openat2"`
	TcpV4Connect          *ebpf.Program `ebpf:"tcp_v4_connect"`
	TraceSchedProcessExec *ebpf.Program `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit *ebpf.Program `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork *ebpf.Program `ebpf:"trace_sched_process_fork"`
	TraceSysEnter         *ebpf.Program `ebpf:"trace_sys_enter"`
}

func (p *BeemonPrograms) Close() error {
	return _BeemonClose(
		p.DoSysOpenat2,
		p.TcpV4Connect,
		p.TraceSchedProcessExec,
		p.TraceSchedProcessExit,
		p.TraceSchedProcessFork,
		p.TraceSysEnter,
	)
}

func _BeemonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed beemon_x86_bpfel.o
var _BeemonBytes []byte
